#ifndef ERRORSTATE_H
#define ERRORSTATE_H

enum class ErrorState : char
{
	ES_SUCCESS = 0x0,
	ES_GAME_PTR_FAILED_NULLCHECK = 0x1,
	ES_GAME_PTR_FAILED_INSTANTIATE = ES_GAME_PTR_FAILED_NULLCHECK << 0x1,
	ES_COUNT
};

#endif // !ERRORSTATE_H

